server.port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/outcons
    username: root
    password: xy234786

  liquibase.change-log:  classpath:/db/changelog-master.xml
db.generator.users.amount: 100
